### ISSUE TITLE
Dont know how to create a betting function.

### ISSUE THREAD

**Issue by CalvinYeung** [CalvinYeung/CalvinYeung.github.io#2]
Hey Anna, I am feeling very lost. I don't know where to even begin my betting function. I feel like I don't have a solid understanding of the material enough to even complete this project... Ever since the weekend that I didn't have my laptop to practice, I have felt very behind. 
````
var bankroll = 1000;

var bet = function bet(betAmount, bankRoll){
	$('#bankroll').click(function(){
	})
}
```
For example, this is my function to deduct the betAmount from my bankRoll which I have declared to equal 1000. I want to be able to deduct the betAmount from the bankRoll as soon as I click the button.

**Comment by annarankin** [comment]
Hey Calvin, you've got the beginning of your feature going - When do you invoke your `bet` function? We're in a meeting at the moment, I'll be free in a little over an hour to go over stuff with you. Until then, think about how you'd get, modify and set your bankroll total.

**Comment by CalvinYeung** [comment]
Okay, I will try. Thank you Anna.
