### ISSUE TITLE
IMG is covering everything

### ISSUE THREAD

**Issue by CalvinYeung** [CalvinYeung/CalvinYeung.github.io#3]
Hey Anna, my img src is covering my entire page and covering my buttons. I cant get it to stay under my layers of buttons. I tried to z-index 0 but that isnt working neither. I also cant seem to get my picture to properly display centered without getting parts of the image getting cut off. I tried to background-size center it too.

**Comment by annarankin** [comment]
Hey Calvin, can you send me your HTML and the CSS you're using to style the image? I want to take a look!

**Comment by CalvinYeung** [comment]
#background{
	position: fixed;
	height: 100%;
	width: 100%;
	z-index: 0;
}


	<article>
		<div id="background" img src="http://1.bp.blogspot.com/-OcljgtsTYsY/UN8_EpyaBlI/AAAAAAAACY4/fJmhmEY33iY/s1600/the_simpsons_gambling_homer_black_jack_broker.JPG"></div>

**Comment by annarankin** [comment]
Gotcha! So, the way I'd resolve this is by adding a `background: url('INSERT IMAGE URL HERE')` CSS rule that applies to the body of your document. That way, the image will serve as the background of your page!

If you want to meet up and talk through it, let me know :+1:

**Comment by CalvinYeung** [comment]
Hm, I just tried it and it isnt working. Do you mind if we meet up?

**Comment by annarankin** [comment]
Sure! Are you in the classroom now? I can meet in about 10 minutes

**Comment by CalvinYeung** [comment]
Im right outside in the main area.

**Comment by annarankin** [comment]
Ok, I'll be down in a few
